# render.yaml
# This file defines the "Infrastructure as Code" for your application on Render.

services:
  # Service 1: The PostgreSQL Database
  # This tells Render to create a free-tier managed database for us.
  - type: pserv
    name: ai-genesis-db
    plan: free
    postgresMajorVersion: 16
    region: oregon # Make sure this matches your web service region

  # Service 2: The Flask Web Service
  # This defines our main application, built from the Dockerfile.
  - type: web
    name: AI-Genesis-Engine
    runtime: docker
    region: oregon # Make sure this matches your database region
    plan: free # Can be upgraded to 'starter' later if you need more resources
    
    # This tells Render what to check to see if your app is healthy and running.
    healthCheckPath: /
    
    # This section defines the environment variables for your web service.
    envVars:
      # This forces Flask to run in a production-ready mode.
      - key: FLASK_CONFIG
        value: prod
      
      # This is the MAGIC line. It links the database to the web service.
      # It takes the connection string from the 'ai-genesis-db' service defined above
      # and makes it available to our app as the 'DATABASE_URL' environment variable.
      - fromDatabase:
          name: ai-genesis-db
          property: connectionString
        key: DATABASE_URL
      
      # We tell Render that all these other keys will be provided manually
      # in the dashboard secrets. 'sync: false' prevents Render from overwriting them.
      - key: SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
